# Generated by Django 4.2.6 on 2024-01-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myada', '0002_remove_studentresult_subject_studentresult_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='course',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myada.subject'),
        ),
    ]
