# Generated by Django 4.2.6 on 2024-01-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myada', '0003_remove_studentresult_course_studentresult_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mat_number',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
